package com.prototype.webapplication.ui.view;

import com.prototype.webapplication.ui.view.mainmenu.MainMenuBar;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewDisplay;
import com.vaadin.spring.annotation.SpringViewDisplay;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

import javax.inject.Inject;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@SpringViewDisplay
public class MainViewDisplay extends CustomComponent implements ViewDisplay {
  
  private final VerticalLayout content = new VerticalLayout();
  
  @Inject
  public MainViewDisplay(MainMenuBar menuBar) {
    final VerticalLayout root = new VerticalLayout();
    root.setSpacing(false);
    root.setSizeFull();
    root.setMargin(false);
    
    root.addComponent(menuBar);
    root.addComponent(content);
    setCompositionRoot(root);
  }
  
  @Override
  public void showView(View view) {
    content.removeAllComponents();
    content.setSpacing(false);
    content.setSizeFull();
    content.setMargin(false);
    content.addComponent((Component) view);
  }
}
